### ISSUE TITLE
Component: Mentioned In 

### ISSUE THREAD

**Issue by madsnedergaard** [Jacse/worlds-best-climate-plan#50]
## Todo

- [x] update icons and make them similar sizes and formats
- [x] Create and style component
- [ ] Consider if the list should be updated
