### ISSUE TITLE
Component: Form

### ISSUE THREAD

**Issue by madsnedergaard** [Jacse/worlds-best-climate-plan#51]
## Todo

- [x] Update and style component
- [ ] Make sure it can be used in both modal and on frontpage
- [ ] Make sure all data is saved to Mailgun
